version: '3.8'

networks:
  jepsen:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/24

services:
  control:
    container_name: jepsen-control
    hostname: control
    image: jepsen-control
    build:
      context: .
      dockerfile: control/Dockerfile
    networks:
      jepsen:
        ipv4_address: 10.100.0.2
    volumes:
      - ../:/jepsen-raft
      - ~/.ssh:/root/.ssh
    environment:
      - LEIN_ROOT=1
    stdin_open: true
    tty: true
    depends_on:
      - n1
      - n2
      - n3
      - n4
      - n5

  n1:
    container_name: jepsen-n1
    hostname: n1
    image: jepsen-node
    build:
      context: ../../..
      dockerfile: jepsen-raft/docker/node/Dockerfile
    networks:
      jepsen:
        ipv4_address: 10.100.0.11
    environment:
      - NODE_ID=n1
      - NODE_HOST=10.100.0.11
      - NODE_PORT=7001
      - CLUSTER_MEMBERS=10.100.0.12:7001,10.100.0.13:7001,10.100.0.14:7001,10.100.0.15:7001
    volumes:
      - n1-data:/opt/fluree-server/data
      - n1-logs:/opt/fluree-server/logs

  n2:
    container_name: jepsen-n2
    hostname: n2
    image: jepsen-node
    build:
      context: ../../..
      dockerfile: jepsen-raft/docker/node/Dockerfile
    networks:
      jepsen:
        ipv4_address: 10.100.0.12
    environment:
      - NODE_ID=n2
      - NODE_HOST=10.100.0.12
      - NODE_PORT=7001
      - CLUSTER_MEMBERS=10.100.0.11:7001,10.100.0.13:7001,10.100.0.14:7001,10.100.0.15:7001
    volumes:
      - n2-data:/opt/fluree-server/data
      - n2-logs:/opt/fluree-server/logs

  n3:
    container_name: jepsen-n3
    hostname: n3
    image: jepsen-node
    build:
      context: ../../..
      dockerfile: jepsen-raft/docker/node/Dockerfile
    networks:
      jepsen:
        ipv4_address: 10.100.0.13
    environment:
      - NODE_ID=n3
      - NODE_HOST=10.100.0.13
      - NODE_PORT=7001
      - CLUSTER_MEMBERS=10.100.0.11:7001,10.100.0.12:7001,10.100.0.14:7001,10.100.0.15:7001
    volumes:
      - n3-data:/opt/fluree-server/data
      - n3-logs:/opt/fluree-server/logs

  n4:
    container_name: jepsen-n4
    hostname: n4
    image: jepsen-node
    build:
      context: ../../..
      dockerfile: jepsen-raft/docker/node/Dockerfile
    networks:
      jepsen:
        ipv4_address: 10.100.0.14
    environment:
      - NODE_ID=n4
      - NODE_HOST=10.100.0.14
      - NODE_PORT=7001
      - CLUSTER_MEMBERS=10.100.0.11:7001,10.100.0.12:7001,10.100.0.13:7001,10.100.0.15:7001
    volumes:
      - n4-data:/opt/fluree-server/data
      - n4-logs:/opt/fluree-server/logs

  n5:
    container_name: jepsen-n5
    hostname: n5
    image: jepsen-node
    build:
      context: ../../..
      dockerfile: jepsen-raft/docker/node/Dockerfile
    networks:
      jepsen:
        ipv4_address: 10.100.0.15
    environment:
      - NODE_ID=n5
      - NODE_HOST=10.100.0.15
      - NODE_PORT=7001
      - CLUSTER_MEMBERS=10.100.0.11:7001,10.100.0.12:7001,10.100.0.13:7001,10.100.0.14:7001
    volumes:
      - n5-data:/opt/fluree-server/data
      - n5-logs:/opt/fluree-server/logs

volumes:
  n1-data:
  n2-data:
  n3-data:
  n4-data:
  n5-data:
  n1-logs:
  n2-logs:
  n3-logs:
  n4-logs:
  n5-logs: