version: '3.8'

networks:
  raft-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.101.0.0/24

services:
  n1:
    container_name: raft-n1
    hostname: n1
    build:
      context: ../..
      dockerfile: jepsen-raft/docker/Dockerfile.node
    environment:
      - NODE_ID=n1
      - TCP_PORT=9001
      - HTTP_PORT=7001
      - TCP_HOST=0.0.0.0
      - HTTP_HOST=0.0.0.0
      - NODES=n1,n2,n3
      - NODE_IPS=n1:10.101.0.11:9001,n2:10.101.0.12:9002,n3:10.101.0.13:9003
    ports:
      - "7001:7001"  # HTTP client port
      - "9001:9001"  # TCP Raft port
    networks:
      raft-network:
        ipv4_address: 10.101.0.11
    volumes:
      - n1-data:/tmp/jepsen-raft-network/n1
      - n1-logs:/var/log/raft
    cap_add:
      - NET_ADMIN  # Allow network manipulation for testing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/debug"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  n2:
    container_name: raft-n2
    hostname: n2
    build:
      context: ../..
      dockerfile: jepsen-raft/docker/Dockerfile.node
    environment:
      - NODE_ID=n2
      - TCP_PORT=9002
      - HTTP_PORT=7002
      - TCP_HOST=0.0.0.0
      - HTTP_HOST=0.0.0.0
      - NODES=n1,n2,n3
      - NODE_IPS=n1:10.101.0.11:9001,n2:10.101.0.12:9002,n3:10.101.0.13:9003
    ports:
      - "7002:7002"
      - "9002:9002"
    networks:
      raft-network:
        ipv4_address: 10.101.0.12
    volumes:
      - n2-data:/tmp/jepsen-raft-network/n2
      - n2-logs:/var/log/raft
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7002/debug"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  n3:
    container_name: raft-n3
    hostname: n3
    build:
      context: ../..
      dockerfile: jepsen-raft/docker/Dockerfile.node
    environment:
      - NODE_ID=n3
      - TCP_PORT=9003
      - HTTP_PORT=7003
      - TCP_HOST=0.0.0.0
      - HTTP_HOST=0.0.0.0
      - NODES=n1,n2,n3
      - NODE_IPS=n1:10.101.0.11:9001,n2:10.101.0.12:9002,n3:10.101.0.13:9003
    ports:
      - "7003:7003"
      - "9003:9003"
    networks:
      raft-network:
        ipv4_address: 10.101.0.13
    volumes:
      - n3-data:/tmp/jepsen-raft-network/n3
      - n3-logs:/var/log/raft
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7003/debug"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  n1-data:
  n2-data:
  n3-data:
  n1-logs:
  n2-logs:
  n3-logs: